Added icon theme inheritance, get-icons argument

diff --git a/set-folder-icon b/set-folder-icon
--- a/set-folder-icon
+++ b/set-folder-icon
@@ -37,6 +37,11 @@ err() {
 	msg "Error:" "$*" >&2
 }
 
+verbose() {
+	[ -t 4 ] || return 0
+	msg "$@" >&4
+}
+
 fatal() {
 	err "$*"
 	exit 1
@@ -45,14 +50,19 @@ fatal() {
 usage() {
 			cat <<- EOF
 			USAGE
-			  $ $PROGNAME [options] -d <folder-name> -t <folder-type>
+			  $ $PROGNAME [-d] FOLDER [-t] TYPE
+			  $ $PROGNAME --delete-icon FOLDER
+			  $ $PROGNAME --get-icon FOLDER
+			  $ $PROGNAME --list
+
 			OPTIONS
-			  -t --type <folder-type>   folder icon type
-			  -d --dir  <folder-path>   directory path
-			     --delete               whether to remove custom icon
-			  -l --list                 show available types
-			  -V --version              print $PROGNAME version and exit
-			  -h --help                 show this help
+			  -t --type TYPE              folder icon type
+			  -d --dir  FOLDER            directory path
+			  --del --delete-icon FOLDER  remove custom icon
+			  -g --get --get-icon FOLDER  show icons
+			  -l --list                   show available types
+			  -V --version                print $PROGNAME version and exit
+			  -h --help                   show this help
 			EOF
 
 			exit "${1:-0}"
@@ -60,8 +70,6 @@ usage() {
 
 _is_valid_type() {
 	local dir_type="$1"
-
-	eval "$(declare_types)"
 
 	for i in "${types[@]}"; do
 		[ "$i" == "$dir_type" ] || continue
@@ -71,9 +79,8 @@ _is_valid_type() {
 	return 1
 }
 
-declare_types() {
-	local dir_type=''
-	local -a types=()
+get_types() {
+	# based on Papyrus icons types
 	local -a valid_types=("activities" "android" "apple" "applications"
 		"arduino" "backup" "books" "cd" "code" "copy-cloud" "desktop"
 		"development" "documents-open" "documents" "download-open" "download"
@@ -88,71 +95,138 @@ declare_types() {
 		"video" "videos-open" "videos" "visiting" "vmware" "wifi"
 		"wine" "yandex-disk") 
 
-	for dir_type in "${valid_types[@]}"; do
-		if [ -e "$THEME_DIR/48x48/places/folder-$dir_type.svg" ]; then
-			types=( "${types[@]}" "$dir_type" )
-		fi
+	for theme_dir in "${THEME_DIRS[@]}"; do
+		for dir_type in "${valid_types[@]}"; do
+			prefix="$theme_dir/48x48/places/folder-$dir_type"
+			if [[ -e "$prefix.svg" || -e "$prefix.png" ]]; then
+				types+=( "$dir_type" )
+			fi
+		done
 	done
 
-	# return array of types
-	declare -p types
+	verbose "Found types ${types[*]}"
 }
 
-get_theme_dir() {
-	local data_dir icons_dir
+get_theme_dirs() {
+	declare -A THEME_DIRS_DICT
+	local -a themes_order=()
 	local -a data_dirs=()
 	local -a icons_dirs=(
-		"$USER_HOME/.icons"
-		"${XDG_DATA_HOME:-$USER_HOME/.local/share}/icons"
+		"$HOME/.icons"
+		"${XDG_DATA_HOME:-$HOME/.local/share}/icons"
 	)
-
-	local _theme_name="$(gsettings get org.gnome.desktop.interface icon-theme)"
-
-	# removes trailing quotes
-	local THEME_NAME="${_theme_name:1:-1}"
 
 	# Get data directories from XDG_DATA_DIRS variable and
 	# convert colon-separated list into bash array
 	IFS=: read -ra data_dirs <<< "${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
 
 	for data_dir in "${data_dirs[@]}"; do
-		[ -d "$data_dir/icons" ] || continue
+		[[ -d "$data_dir/icons" ]] || continue
 		icons_dirs=( "${icons_dirs[@]}" "${data_dir%/}/icons" )
 	done
 
-	for icons_dir in "${icons_dirs[@]}"; do
-		[ -f "$icons_dir/$THEME_NAME/index.theme" ] || continue
-		printf '%s' "$icons_dir/$THEME_NAME"
-		return 0
+	# removes trailing quotes
+	THEME_NAME="$(gsettings get org.gnome.desktop.interface icon-theme)"
+	THEME_NAME="${THEME_NAME//\'/}"
+	themes_order+=( "$THEME_NAME" )
+
+	# set first theme dir
+	for icon_dir in "${icons_dirs[@]}"; do
+		theme_dir="$icon_dir/$THEME_NAME"
+		if [[ -d "$theme_dir" && -f "$theme_dir/index.theme" ]]; then
+			THEME_DIRS_DICT[$THEME_NAME]="$theme_dir"
+		fi
 	done
 
-	return 1
+	CONTINUE=1
+	while [[ $CONTINUE -eq 1 ]]; do
+		# get subthemes
+		for theme_dir in "${THEME_DIRS_DICT[@]}"; do
+			theme_index="$theme_dir/index.theme"
+			if grep -qoP "(?<=^Inherits=).+" "$theme_index"; then
+				IFS=, read -ra subthemes <<< "$(grep -oP -m1 "(?<=^Inherits=).+" "$theme_index")"
+				for theme_name in "${subthemes[@]}"; do
+					[[ -d "${THEME_DIRS_DICT[$theme_name]}" ]] || THEME_DIRS_DICT[$theme_name]=""
+				done
+			fi
+		done
+
+		CONTINUE=0
+		for theme_dir in "${THEME_DIRS_DICT[@]}"; do
+			if [[ -z $theme_dir ]]; then
+				CONTINUE=1
+				break
+			fi
+		done
+
+		# search theme dirs
+		for theme_name in "${!THEME_DIRS_DICT[@]}"; do
+			[[ -d "${THEME_DIRS_DICT[$theme_name]}" ]] && continue
+			themes_order+=( "$theme_name" )
+			for icon_dir in "${icons_dirs[@]}"; do
+				theme_dir="$icon_dir/$theme_name"
+				if [[ -d "$theme_dir" && -f "$theme_dir/index.theme" ]]; then
+					THEME_DIRS_DICT[$theme_name]="$theme_dir"
+				fi
+			done
+
+			[[ -z "${THEME_DIRS_DICT[$theme_name]}" ]] && fatal "Theme $theme_name not found"
+		done
+	done
+
+	verbose "Found themes ${themes_order[*]}"
+	for theme_name in "${themes_order[@]}"; do
+		THEME_DIRS+=( "${THEME_DIRS_DICT[$theme_name]}" )
+	done
 }
 
 list_types() {
 	local dir_type=''
 
-	eval "$(declare_types)"
+	if [[ "${#types[@]}" -eq 0 ]]; then
+		fatal "No type found in ${THEME_DIRS[*]}"
+	fi
 
-	for i in ${types[@]}; do echo "$i"; done | column
+	if [ -t 1 ]; then
+		cat <<- EOF
+		List of available types:
+
+		$(printf "\n%s" "${types[@]}" | column)
+		EOF
+	else
+		printf "\n%s" "${types[@]}"	
+	fi
 }
 
 change_icon () {
-		_is_valid_type "$SELECTED_TYPE" || {
-			fatal "Unable to find '$SELECTED_TYPE' type in '$THEME_DIR'"
-		}
-		if [[ -d "$SELECTED_FOLDER" ]]; then
-			gio set -t string "$SELECTED_FOLDER" metadata::custom-icon-name "folder-${SELECTED_TYPE}"
-		else
-			fatal "'$SELECTED_FOLDER' is not a path to a directory"
-		fi
+	local folder="$1"
+	local type="$2"
+
+	_is_valid_type "$type" || fatal "Unable to find '$type' type in ${THEME_DIRS[*]}"
+
+	if [[ -d "$folder" ]]; then
+		gio set -t string "$folder" metadata::custom-icon-name "folder-${TYPE}"
+	else
+		fatal "'$folder' is not a path to a directory"
+	fi
+}
+
+get_icon () {
+	local folder="$1"
+
+	if [[ -d "$folder" ]]; then
+		gio info -a standard::name,standard::icon,metadata::custom-icon-name "$folder"
+	else
+		fatal "'$folder' is not a path to a directory"
+	fi		
 }
 
 delete_icon () {
-		if [[ -d "$SELECTED_FOLDER" ]]; then
-			gio set -d "$SELECTED_FOLDER" metadata::custom-icon-name 
+	local folder="$1"
+		if [[ -d "$folder" ]]; then
+			gio set -d "$folder" metadata::custom-icon-name 
 		else
-			fatal "'$SELECTED_FOLDER' is not a path to a directory"
+			fatal "'$folder' is not a path to a directory"
 		fi
 }
 
@@ -162,15 +236,16 @@ parse_args() {
 		usage 2
 	fi
 
+	# parse kwargs
 	while [ $# -gt 0 ]; do
 		case "$1" in
 			--dir*|-d*)
 				if [[ "$1" != = ]]; then shift; fi
-				SELECTED_FOLDER="${1#*=}"
+				FOLDER="${1#*=}"
 				;;
 			--type*|-t*)
 				if [[ "$1" != = ]]; then shift; fi
-				SELECTED_TYPE="${1#*=}"
+				TYPE="${1#*=}"
 				;;
 			--help|-h)
 				usage 0
@@ -179,49 +254,78 @@ parse_args() {
 				printf "%s %s\n" "$PROGNAME" "$VERSION"
 				exit 0
 				;;
-			--list|-l)
-				if [ -t 1 ]; then
-					cat <<- EOF
-					List of available types:
-
-					$(list_types)
-					EOF
-				else
-					list_types
-				fi
-				exit 0
+			--verbose)
+				VERBOSE=1
 				;;
-			--delete)
-				DELETE_ICON=1
+			--list|-l)
+				OPERATION="list"
+				;;
+			--del*)
+				OPERATION="delete"
+				;;
+			-g|--get*)
+				OPERATION="get"
 				;;
 			-*)
 				echo "illegal option -- '$1'"
 				usage 2
 				;;
 			*)
-				if [[ -d "$1" && -z "$SELECTED_FOLDER" ]]; then
-					SELECTED_FOLDER="$1"
-				elif [[ -z "$SELECTED_TYPE" ]]; then
-					SELECTED_TYPE="$1"
-				else
-					SELECTED_FOLDER="$1"
-				fi
+				args+=( "$1" )
 				;;
 		esac
 		shift
 	done
+
+	# parse args
+	for arg in "${args[@]}"; do
+		if [[ -d "$arg" && -z "$FOLDER" ]]; then
+			FOLDER="$arg"
+		elif [[ -z "$TYPE" ]]; then
+			TYPE="$arg"
+		else
+			FOLDER="$arg"
+		fi
+	done
+
+	if [[ -z "$OPERATION" ]]; then
+		OPERATION="change"
+	fi
 }
 
 main() {
-	declare SELECTED_TYPE='' SELECTED_FOLDER='' DELETE_ICON=0
-	declare THEME_DIR="$(get_theme_dir)"
+	local FOLDER TYPE OPERATION
+	declare -a THEME_DIRS
+	declare -a types
+
+	declare -i VERBOSE="${VERBOSE:-0}"
 
 	parse_args "${ARGS[@]}"
-	if [[ DELETE_ICON -eq 1 ]]; then
-		delete_icon
-	else
-		change_icon
+
+	if [[ "$VERBOSE" -eq "1" ]]; then
+		# open a file descriptor for verbose messages
+		exec 4>&1
+		# close it before exiting
+		trap 'exec 4>&-' EXIT HUP INT TERM
 	fi
+
+	get_theme_dirs
+	get_types
+
+	case "$OPERATION" in
+		delete)
+			delete_icon "$FOLDER"
+			;;
+		get)
+			get_icon "$FOLDER"
+			;;
+		list)
+			list_types
+			;;
+		change)
+			change_icon "$FOLDER" "$TYPE"
+			;;
+	esac
 
 	exit 0
 }
