Deduplicate listed icons, added --force parameter

diff --git a/set-folder-icon b/set-folder-icon
--- a/set-folder-icon
+++ b/set-folder-icon
@@ -22,10 +22,10 @@ set -o errexit \
 	-o pipefail
 
 PROGNAME="$(basename "${BASH_SOURCE[0]}")"
-VERSION="0.1.1"
+PROGVERSION="0.1.2"
 
 readonly PROGNAME
-readonly VERSION
+readonly PROGVERSION
 readonly -a ARGS=("$@")
 
 
@@ -59,6 +59,7 @@ usage() {
 			  -t --type TYPE              folder icon type
 			  -d --dir  FOLDER            directory path
 			  --del --delete-icon FOLDER  remove custom icon
+			  -f --force                  ignore type validity check
 			  -g --get --get-icon FOLDER  show icons
 			  -l --list                   show available types
 			  -V --version                print $PROGNAME version and exit
@@ -81,6 +82,7 @@ _is_valid_type() {
 
 get_types() {
 	# based on Papyrus icons types
+	local -a duptypes=()
 	local -a valid_types=("activities" "android" "apple" "applications"
 		"arduino" "backup" "books" "cd" "code" "copy-cloud" "desktop"
 		"development" "documents-open" "documents" "download-open" "download"
@@ -93,16 +95,21 @@ get_types() {
 		"remove-open" "remote" "script" "snap" "steam" "sync" "syncthing"
 		"tar" "templates-open" "templates" "torrent" "unlocked" "vbox"
 		"video" "videos-open" "videos" "visiting" "vmware" "wifi"
-		"wine" "yandex-disk") 
+		"wine" "yandex-disk")
 
 	for theme_dir in "${THEME_DIRS[@]}"; do
 		for dir_type in "${valid_types[@]}"; do
 			prefix="$theme_dir/48x48/places/folder-$dir_type"
 			if [[ -e "$prefix.svg" || -e "$prefix.png" ]]; then
-				types+=( "$dir_type" )
+				duptypes+=( "$dir_type" )
 			fi
 		done
 	done
+
+	# remove duplicates
+	while IFS= read -r -d '' item;	do
+		types+=("$item")
+	done < <(printf "%s\0" "${duptypes[@]}" | sort -uz)
 
 	verbose "Found types ${types[*]}"
 }
@@ -202,10 +209,17 @@ change_icon () {
 	local folder="$1"
 	local type="$2"
 
-	_is_valid_type "$type" || fatal "Unable to find '$type' type in ${THEME_DIRS[*]}"
+	if [[ "$FORCE" == "0" ]]; then
+		_is_valid_type "$type" || fatal "Unable to find '$type' type in ${THEME_DIRS[*]}"
+	fi
 
 	if [[ -d "$folder" ]]; then
-		gio set -t string "$folder" metadata::custom-icon-name "folder-${TYPE}"
+		if [[ "$FORCE" == "1" ]]; then
+			_type="$type"
+		else
+			_type="folder-${type}"
+		fi
+		gio set -t string "$folder" metadata::custom-icon-name "$_type"
 	else
 		fatal "'$folder' is not a path to a directory"
 	fi
@@ -251,11 +265,14 @@ parse_args() {
 				usage 0
 				;;
 			--version|-V)
-				printf "%s %s\n" "$PROGNAME" "$VERSION"
+				printf "%s %s\n" "$PROGNAME" "$PROGVERSION"
 				exit 0
 				;;
 			--verbose)
 				VERBOSE=1
+				;;
+			--force|-f)
+				FORCE=1
 				;;
 			--list|-l)
 				OPERATION="list"
@@ -299,6 +316,7 @@ main() {
 	declare -a types
 
 	declare -i VERBOSE="${VERBOSE:-0}"
+	declare -i FORCE=0
 
 	parse_args "${ARGS[@]}"
 
